# Generated by Django 6.0.5 on 2026-05-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('sender_bank', models.CharField(blank=True, max_length=100)),
                ('sender_account', models.CharField(blank=True, max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('recipient_bank', models.CharField(max_length=100)),
                ('recipient_account', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('transfer_reference', models.CharField(blank=True, max_length=200)),
                ('transfer_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='blood_requests.requestdonormatch')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='blood_requests.bloodrequest')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
