# Generated by Django 6.0.5 on 2026-05-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('response_rate', models.FloatField(default=0.0)),
                ('availability_score', models.FloatField(default=0.5)),
                ('reliability_score', models.FloatField(default=0.5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('n8n_donor_id', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(choices=[('n8n', 'N8N'), ('direct', 'Direct'), ('ml', 'ML Discovered')], default='n8n', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donors',
            },
        ),
        migrations.CreateModel(
            name='DonorAvailabilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField()),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('check_method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('api', 'API')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_logs', to='donors.donor')),
            ],
            options={
                'db_table': 'donor_availability_logs',
            },
        ),
    ]
