# Generated by Django 6.0.5 on 2026-05-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units_needed', models.IntegerField(default=1)),
                ('urgency', models.CharField(choices=[('critical', 'Critical - Immediate'), ('urgent', 'Urgent - Within 2 hours'), ('standard', 'Standard - Within 24 hours')], default='standard', max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('patient_condition', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_n8n', 'Sent to N8N'), ('ml_processing', 'ML Processing'), ('donors_found', 'Donors Found'), ('donor_selected', 'Donor Selected'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('n8n_workflow_id', models.CharField(blank=True, max_length=200, null=True)),
                ('n8n_execution_id', models.CharField(blank=True, max_length=200, null=True)),
                ('handled_by_ml', models.BooleanField(default=False)),
                ('ml_confidence_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blood_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDonorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('availability_checking', 'Checking Availability'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('selected', 'Selected by Hospital'), ('rejected', 'Rejected by Hospital'), ('completed', 'Completed')], default='proposed', max_length=30)),
                ('match_score', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(null=True)),
                ('availability_checked_at', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request_donor_matches',
            },
        ),
    ]
