# Generated by Django 6.0.5 on 2026-05-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='requestdonormatch',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_matches', to='donors.donor'),
        ),
        migrations.AddField(
            model_name='requestdonormatch',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_matches', to='blood_requests.bloodrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='requestdonormatch',
            unique_together={('request', 'donor')},
        ),
    ]
